<?
$PERM["personal"]["5"]="R";
$PERM["personal"]["6"]="R";
$PERM["personal"]["10"]="R";
$PERM["personal"]["8"]="R";
$PERM["personal"]["9"]="R";
$PERM["personal"]["7"]="R";
$PERM["personal"]["*"]="D";
$PERM["/"]["*"]="R";
?>